version: "1.13.1"
services:
  consul:
    image: "consul:1.13.1"
    restart: always
    network_mode: host
    volumes:
      - ./data:/consul/data
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: "agent -server -bind=127.0.0.1 -client=127.0.0.1 -ui -bootstrap-expect=1 -node=agent-0 -enable-script-checks=true"
