version: "1.13.1"
services:
  consul:
    image: "consul:1.13.1"
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./docker_volume/data:/consul/data
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: "agent -server -bind=0.0.0.0 -client=0.0.0.0 -ui -bootstrap-expect=1 -node=agent-0 -enable-script-checks=true"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: 3
